/**
 * "Kode" practice mode: TypeScript and Svelte one-liners, heavy on
 * `{ } [ ] ( ) => ; : ' = ! & |`. No template literals — the backtick is a
 * dead key on this layout and must never appear in practice text.
 */
export const CODE_LINES: readonly string[] = [
	"const user = { id: 42, name: 'Kari' };",
	'if (items.length > 0) { return items[0]; }',
	'export function sum(a: number, b: number) { return a + b; }',
	'const ids = rows.map((r) => r.id).filter(Boolean);',
	'type Props = { title: string; open?: boolean };',
	'let total = prices.reduce((acc, p) => acc + p, 0);',
	'const isOk = res.status === 200 && data !== null;',
	"import { onMount } from 'svelte';",
	'const [first, ...rest] = list;',
	"throw new Error('Mangler id: ' + id);",
	'let { name, age = 0 } = person;',
	'const found = list.find((x) => x.id === target);',
	'export interface State { count: number; ready: boolean; }',
	"const safe = value ?? 'ukjent';",
	'if (!user || !user.id) { return null; }',
	'const sorted = [...items].sort((a, b) => a.pos - b.pos);',
	'let count = $state(0);',
	'let doubled = $derived(count * 2);',
	"$effect(() => { console.log('count', count); });",
	'let { children } = $props();',
	'export const load = async ({ params }) => { return { id: params.id }; };',
	"const isValid = typeof input === 'string' && input.length > 0;",
	'function toggle(open: boolean) { return !open; }',
	'const map = new Map<string, number>();',
	'const set = new Set([1, 2, 3]);',
	'const json = JSON.stringify({ a: 1, b: 2 });',
	'const parsed = JSON.parse(raw) as Config;',
	'try { await save(data); } catch (err) { console.error(err); }',
	'const clamp = (n: number, min: number, max: number) => Math.min(Math.max(n, min), max);',
	'export default class Store { #items: Item[] = []; }',
	"const label = open ? 'Lukk' : 'Åpne';",
	"const el = document.querySelector('.stage');",
	'if (event.metaKey || (event.ctrlKey && !event.altKey)) { return; }',
	'const key = event.key.length === 1 ? event.key : null;',
	'const handler = (e: KeyboardEvent) => { e.preventDefault(); };',
	'const chars: Record<string, number> = {};',
	'const avg = (sum: number, n: number) => (n === 0 ? 0 : sum / n);',
	'<input bind:value={text} on:keydown={handleKey} />',
	'<button class="btn" onclick={next}>Ny tekst</button>',
	'export let settings: Settings = DEFAULT_SETTINGS;',
	'const isTypable = (c: string) => charMap.has(c);',
	"const result = a && b ? 'begge' : a || b ? 'en' : 'ingen';",
	'const entries = Object.entries(chars).filter(([, v]) => v.attempts > 0);',
	"export type Mode = 'tekst' | 'kode' | 'avlast' | 'svake';",
	'const nums: number[] = [1, 2, 3, 4, 5];',
	"if (!ready) { throw new Error('Ikke klar!'); }"
];
