/**
 * "Tekst" practice mode, English content for the US QWERTY layout. See
 * {@link ./texts} for the Norwegian equivalent.
 */
export const TEXTS_EN: readonly string[] = [
	'The rain kept falling, so we stayed inside and played cards.',
	'She biked across the valley over four days and slept in a tent each night.',
	'The coffee was cold, but the conversation at the kitchen table was warm.',
	'When the fjord lies flat in the morning, you can only hear the gulls.',
	'He forgot his keys at the office and had to wait for the caretaker.',
	'The tram was late again, so I walked the last stretch on foot.',
	'We found a small cabin by the lake and fished until the sun went down.',
	'The kids built a snowman with a carrot nose and twigs for arms.',
	'Learning to type with all ten fingers takes time, but it pays off.',
	'He forgot his umbrella at home and got soaked on the way to the bus.',
	'Grandma always makes rice pudding with cinnamon and sugar at Christmas.',
	'The weather turned suddenly, and we found ourselves in a hailstorm.',
	'Our neighborhood has a small library where you can trade books for free.',
	'The hike took longer than planned because the trail was icy.',
	'I prefer tea over coffee once the evening gets late.',
	'Remember to water the plants while we are at the cabin.',
	'The children played hide and seek in the yard until it got dark.',
	'Fresh bread smells drift from the bakery on the corner every morning.',
	'He finally caught a trout after three hours out on the boat.',
	'We drove along the coast and stopped to watch the waves.',
	'School started an hour late because of thick fog.',
	'I need to remember to pick up the package before the post office closes.',
	'The cat slept all afternoon in the sunny spot by the window.',
	'They built a new footbridge across the river this summer.',
	'The teacher handed back the tests with a small smile.',
	'The wind caught the sail, and the boat shot forward toward the island.',
	'He practiced guitar every evening after dinner for two months.',
	'We picked blueberries in the woods behind the cabin all Saturday.',
	'Breakfast was oatmeal, an apple, and a little cinnamon.',
	'The train was packed, so we had to stand the whole way into town.',
	'The garden needs tending before winter sets in for good.',
	'I found an old diary in the attic full of strange stories.',
	'The staff got Wednesday afternoon off for a team event.',
	'A gull screamed loudly from the roof right outside the office window.',
	'We lit a fire on the beach and grilled hot dogs late into the night.',
	'He forgot to turn off the light before he left the office.',
	'The Sunday walk ended with hot chocolate and waffles at the cafe.',
	'I think February is the longest month of them all.',
	'The bike got a flat tire right before we were about to head home.',
	'At midnight the sun still hung low over the mountains up north.',
	'He glued the broken vase back together with a lot of patience.',
	'We shared a large pizza and talked about old memories.',
	'There was a line at the toll booth through the whole morning rush.'
];
