/**
 * "Tekst" practice mode: everyday Norwegian sentences, deliberately
 * including æ, ø and å. No dead-key characters, em dashes or curly quotes —
 * everything here must be typable on the Norwegian PC layout.
 */
export const TEXTS: readonly string[] = [
	'Blåbærsyltetøy på knekkebrød er en undervurdert frokost.',
	'Det regnet hele dagen, så vi ble inne og spilte kort.',
	'Hun syklet over fjellet på fire dager og sov i telt hver natt.',
	'Kaffen var kald, men praten ved kjøkkenbordet var varm.',
	'Når fjorden ligger blank om morgenen, høres bare måkene.',
	'Jeg glemte nøklene på jobben og måtte vente på vaktmesteren.',
	'Trikken var forsinket igjen, så jeg gikk den siste biten.',
	'Vi fant en liten hytte ved vannet og fisket til solen gikk ned.',
	'Barna bygde en snømann med gulrotnese og kvist til armer.',
	'Å lære seg å skrive med alle ti fingre tar tid, men lønner seg.',
	'Han glemte paraplyen hjemme og ble våt til skinnet på vei til bussen.',
	'Bestemor lager alltid rømmegrøt med kanel og sukker til jul.',
	'Været skiftet brått, og plutselig sto vi midt i et haglvær.',
	'Nabolaget vårt har et lite bibliotek der man kan bytte bøker gratis.',
	'Fjellturen tok lengre tid enn planlagt fordi stien var glatt av is.',
	'Jeg foretrekker te fremfor kaffe når kvelden blir sen.',
	'Du må huske å vanne blomstene mens vi er på hytta.',
	'Ungene lekte gjemsel i hagen til det ble mørkt.',
	'Det lukter nybakt brød fra bakeriet på hjørnet hver morgen.',
	'Han fikk endelig fisket opp en ørret etter tre timer i båten.',
	'Vi kjørte langs kysten og stoppet for å se på bølgene.',
	'Skolen startet en time senere på grunn av tett tåke.',
	'Jeg må huske å hente pakken før posten stenger klokken fire.',
	'Katten sov hele ettermiddagen i vindaugskarmen i solen.',
	'De bygde en ny gangbro over elva i sommer.',
	'Læreren delte ut prøvene med et lite smil om munnen.',
	'Vinden tok tak i seilet, og båten skjøt fart mot øya.',
	'Han øvde på gitar hver kveld etter middag i to måneder.',
	'Vi plukket tyttebær i skogen bak hytta hele lørdagen.',
	'Frokosten besto av havregrøt, eple og litt kanel.',
	'Toget var stappfullt, så vi måtte stå hele veien til Oslo.',
	'Hagen trenger stell før vinteren kommer for alvor.',
	'Jeg fant en gammel dagbok på loftet full av rare historier.',
	'De ansatte fikk fri onsdag ettermiddag for en teambygging.',
	'Måken skrek høyt fra taket like ved kontorvinduet.',
	'Vi lagde bål på stranden og grillet pølser til sent på kveld.',
	'Han glemte å skru av lyset før han forlot kontoret.',
	'Søndagsturen endte med varm sjokolade og vafler på kafeen.',
	'Jeg synes februar er den lengste måneden av alle.',
	'Sykkelen fikk punktering rett før vi skulle dra hjemover.',
	'Ved midnatt sto sola fortsatt lavt over fjellene i nord.',
	'Han limte sammen den knuste vasen med stor tålmodighet.',
	'Vi delte en stor pizza og snakket om gamle minner.',
	'Det var kø ved bommen hele morgenrushet på motorveien.'
];
